// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Infrastructure.Data;

namespace backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("backend.Models.Autochasing", b =>
                {
                    b.Property<DateTime?>("Lastautochasing")
                        .HasColumnType("datetime")
                        .HasColumnName("lastautochasing");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.ToTable("autochasing");
                });

            modelBuilder.Entity("backend.Models.BulkChasingEmailbuffer", b =>
                {
                    b.Property<string>("Bodytext")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bodytext");

                    b.Property<string>("ChasingdocFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chasingdocFile");

                    b.Property<string>("Emailheader")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emailheader");

                    b.Property<string>("Invoicefile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invoicefile");

                    b.Property<int?>("Ppid")
                        .HasColumnType("int")
                        .HasColumnName("ppid");

                    b.Property<bool?>("Sendemail")
                        .HasColumnType("bit")
                        .HasColumnName("sendemail");

                    b.Property<int?>("Templateid")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("username");

                    b.ToTable("BulkChasingEmailbuffer");
                });

            modelBuilder.Entity("backend.Models.BusinessSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("NoRrr")
                        .HasColumnType("bit")
                        .HasColumnName("NoRRR");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("Putby")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Puttype")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("puttype");

                    b.Property<decimal?>("Putvalue")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("BusinessSources");
                });

            modelBuilder.Entity("backend.Models.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationTimestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChangeLog");
                });

            modelBuilder.Entity("backend.Models.ChasingLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LatePaymentInvoiceDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("LatePaymentInvoiceDocumentID");

                    b.Property<int?>("LatePaymentInvoiceNumber")
                        .HasColumnType("int");

                    b.Property<int>("LeasePaymentPointId")
                        .HasColumnType("int")
                        .HasColumnName("LeasePaymentPointID");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("TemplateID");

                    b.HasKey("Id");

                    b.HasIndex("LeasePaymentPointId");

                    b.HasIndex("TemplateId");

                    b.ToTable("ChasingLetters");
                });

            modelBuilder.Entity("backend.Models.CheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CheckListItems");
                });

            modelBuilder.Entity("backend.Models.ContactDatum", b =>
                {
                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Account_Ref");

                    b.Property<bool?>("Dontautoasign")
                        .HasColumnType("bit")
                        .HasColumnName("dontautoasign");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email_Address");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Lastemail")
                        .HasColumnType("datetime")
                        .HasColumnName("lastemail");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("NotesId")
                        .HasColumnType("int")
                        .HasColumnName("NotesID");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Other_Names");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.ToTable("ContactData");
                });

            modelBuilder.Entity("backend.Models.ContactNote", b =>
                {
                    b.Property<int?>("Contactid")
                        .HasColumnType("int");

                    b.Property<string>("Custref")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("custref");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Leaseid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Nextcall")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesType")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("Ppid")
                        .HasColumnType("int")
                        .HasColumnName("PPid");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.ToTable("ContactNotes");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Account_Ref");

                    b.Property<bool?>("EmailInvoices")
                        .HasColumnType("bit");

                    b.Property<string>("InvAddress1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Inv_address1");

                    b.Property<string>("InvAddress2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Inv_address2");

                    b.Property<string>("InvAddress3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Inv_address3");

                    b.Property<string>("InvAddress4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Inv_address4");

                    b.Property<string>("InvAddress5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Inv_address5");

                    b.Property<string>("InvName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("inv_name");

                    b.Property<int?>("LegalStatusId")
                        .HasColumnType("int")
                        .HasColumnName("LegalStatusID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PaperInvoices")
                        .HasColumnType("bit");

                    b.Property<bool?>("Paperless")
                        .HasColumnType("bit")
                        .HasColumnName("paperless");

                    b.Property<int?>("PrimaryContactId")
                        .HasColumnType("int")
                        .HasColumnName("PrimaryContactID");

                    b.Property<string>("SageAddress1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_address_1");

                    b.Property<string>("SageAddress2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_address_2");

                    b.Property<string>("SageAddress3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_address_3");

                    b.Property<string>("SageAddress4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_address_4");

                    b.Property<string>("SageAddress5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_address_5");

                    b.Property<decimal?>("SageBalance")
                        .HasColumnType("money")
                        .HasColumnName("sage_balance");

                    b.Property<string>("SageDelAddress1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_del_address_1");

                    b.Property<string>("SageDelAddress2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_del_address_2");

                    b.Property<string>("SageDelAddress3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_del_address_3");

                    b.Property<string>("SageDelAddress4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_del_address_4");

                    b.Property<string>("SageDelAddress5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_del_address_5");

                    b.Property<string>("SageEMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_e_mail");

                    b.Property<DateTime?>("SageLastpaid")
                        .HasColumnType("date")
                        .HasColumnName("sage_lastpaid");

                    b.Property<string>("SageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_name");

                    b.Property<string>("SageWww")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sage_www");

                    b.Property<int?>("SecondaryContactId")
                        .HasColumnType("int")
                        .HasColumnName("SecondaryContactID");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("SectorID");

                    b.HasKey("Id");

                    b.HasIndex("LegalStatusId");

                    b.HasIndex("SectorId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("backend.Models.CustomerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Note")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerHistory");
                });

            modelBuilder.Entity("backend.Models.Debug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Debug");
                });

            modelBuilder.Entity("backend.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Account_Ref");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("backend.Models.Emailreport", b =>
                {
                    b.Property<string>("Attachment1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attachment1");

                    b.Property<string>("Attachment2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attachment2");

                    b.Property<string>("Attachment3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attachment3");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<string>("Contactname")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("contactname");

                    b.Property<string>("Custref")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("custref");

                    b.Property<string>("Emailaddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("emailaddress");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("username");

                    b.ToTable("emailreport");
                });

            modelBuilder.Entity("backend.Models.EquipmentCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentConditions");
                });

            modelBuilder.Entity("backend.Models.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("backend.Models.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Account_Ref");

                    b.Property<decimal?>("AnnualServiceFeeAmount")
                        .HasColumnType("money");

                    b.Property<int>("BusinessSourceId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessSourceID");

                    b.Property<int?>("BusinessSourceItemId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessSourceItemID");

                    b.Property<int>("ContactChasingLetter1")
                        .HasColumnType("int");

                    b.Property<int>("ContactChasingLetter2")
                        .HasColumnType("int");

                    b.Property<int>("ContactChasingLetter3")
                        .HasColumnType("int");

                    b.Property<int>("ContactChasingLetter4")
                        .HasColumnType("int");

                    b.Property<int>("ContactEpcchasingLetter1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactEPCChasingLetter1")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("ContactEpcchasingLetter2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactEPCChasingLetter2")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("ContactEpcchasingLetter3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactEPCChasingLetter3")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("ContactLatePaymentChasingLetter1")
                        .HasColumnType("int");

                    b.Property<int>("ContactLatePaymentChasingLetter2")
                        .HasColumnType("int");

                    b.Property<int>("ContactLatePaymentChasingLetter3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("ContactWelcomeLetter")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("FacilityFeeAmount")
                        .HasColumnType("money");

                    b.Property<int?>("InsuranceDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("InsuranceDocumentID");

                    b.Property<string>("InvoiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeasePeriod")
                        .HasColumnType("int");

                    b.Property<double>("LeaseRate")
                        .HasColumnType("float");

                    b.Property<int>("Leasetype")
                        .HasColumnType("int")
                        .HasColumnName("leasetype");

                    b.Property<int>("LegalStatusId")
                        .HasColumnType("int")
                        .HasColumnName("LegalStatusID");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("money");

                    b.Property<int>("PaymentFrequency")
                        .HasColumnType("int");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("PaymentStartDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Pepfee")
                        .HasColumnType("bit")
                        .HasColumnName("PEPFee");

                    b.Property<decimal?>("PepfeeAmount")
                        .HasColumnType("money")
                        .HasColumnName("PEPFeeAmount");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int?>("Putletterid")
                        .HasColumnType("int")
                        .HasColumnName("putletterid");

                    b.Property<int?>("Rrrfrequency")
                        .HasColumnType("int")
                        .HasColumnName("RRRfrequency");

                    b.Property<int?>("Rrrs")
                        .HasColumnType("int")
                        .HasColumnName("RRRs");

                    b.Property<int?>("RrrsagreementDocId")
                        .HasColumnType("int")
                        .HasColumnName("RRRsagreementDocID");

                    b.Property<DateTime?>("Rrrstartdate")
                        .HasColumnType("date")
                        .HasColumnName("RRRstartdate");

                    b.Property<double>("SecondaryTermPaymentAmount")
                        .HasColumnType("float");

                    b.Property<int>("SecondaryTermPaymentFrequency")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryTermPeriod")
                        .HasColumnType("int");

                    b.Property<double>("SecondaryTermSplit")
                        .HasColumnType("float");

                    b.Property<bool>("SecondaryTermSplitEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SectorId")
                        .HasColumnType("int")
                        .HasColumnName("SectorID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("SupplierInvoiceValue")
                        .HasColumnType("money");

                    b.Property<bool>("TerminationNotified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TerminationNotifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Terminationnoticeid")
                        .HasColumnType("int")
                        .HasColumnName("terminationnoticeid");

                    b.Property<double>("YeildPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BusinessSourceId");

                    b.HasIndex("BusinessSourceItemId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LegalStatusId");

                    b.HasIndex("SectorId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("backend.Models.LeaseCheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CheckListItemId")
                        .HasColumnType("int")
                        .HasColumnName("CheckListItemID");

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<string>("EditedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CheckListItemId");

                    b.HasIndex("LeaseId");

                    b.ToTable("LeaseCheckListItems");
                });

            modelBuilder.Entity("backend.Models.LeaseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentID");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.Property<bool>("Note")
                        .HasColumnType("bit");

                    b.Property<int?>("PaymentPointId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentPointID");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LeaseId");

                    b.HasIndex("PaymentPointId");

                    b.ToTable("LeaseHistory");
                });

            modelBuilder.Entity("backend.Models.LeaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("EquipmentConditionId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentConditionID");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentTypeID");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.Property<string>("Make")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentConditionId");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("LeaseId");

                    b.ToTable("LeaseItems");
                });

            modelBuilder.Entity("backend.Models.LeasePaymentPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Account_Ref");

                    b.Property<string>("AmountPaid")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("amount_paid");

                    b.Property<bool>("AnnualServiceFee")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AnnualServiceFeeAmount")
                        .HasColumnType("money");

                    b.Property<byte>("ChasingStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("date")
                        .HasColumnName("date_paid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("FacilityFee")
                        .HasColumnType("bit");

                    b.Property<decimal?>("FacilityFeeAmount")
                        .HasColumnType("money");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InvoiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("InvoiceDocumentID");

                    b.Property<bool>("InvoiceEmailed")
                        .HasColumnType("bit");

                    b.Property<int?>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<bool>("InvoicePrinted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InvoiceTotal")
                        .HasColumnType("money");

                    b.Property<decimal?>("LatePaymentAdministrationChargesAmount")
                        .HasColumnType("money");

                    b.Property<bool>("LatePaymentExcused")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LatePaymentInterestChargesAmount")
                        .HasColumnType("money");

                    b.Property<int?>("LatePaymentInvoiceDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("LatePaymentInvoiceDocumentID");

                    b.Property<int?>("LatePaymentInvoiceNumber")
                        .HasColumnType("int");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int")
                        .HasColumnName("LeaseID");

                    b.Property<bool?>("ManualPaidCorrection")
                        .HasColumnType("bit")
                        .HasColumnName("manual_paid_correction");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("bit");

                    b.Property<bool>("Pepfee")
                        .HasColumnType("bit")
                        .HasColumnName("PEPFee");

                    b.Property<decimal?>("PepfeeAmount")
                        .HasColumnType("money")
                        .HasColumnName("PEPFeeAmount");

                    b.Property<DateTime?>("RemAdvReceivedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Reminded")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RentalAmount")
                        .HasColumnType("money");

                    b.Property<decimal?>("SettlementAmount")
                        .HasColumnType("money");

                    b.Property<bool>("Terminated")
                        .HasColumnType("bit");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId");

                    b.ToTable("LeasePaymentPoints");
                });

            modelBuilder.Entity("backend.Models.MarketingUrl", b =>
                {
                    b.Property<bool?>("Activetoday")
                        .HasColumnType("bit");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mdescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mdescription");

                    b.Property<string>("ResultUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResultURL");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urlemailtext")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("URLEmailtext");

                    b.Property<string>("Urlstr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URLstr");

                    b.ToTable("MarketingURLs");
                });

            modelBuilder.Entity("backend.Models.PaymentFrequency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentFrequencies");
                });

            modelBuilder.Entity("backend.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("backend.Models.PrintDoc", b =>
                {
                    b.Property<string>("Docname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("docname");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("templateID");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.ToTable("PrintDocs");
                });

            modelBuilder.Entity("backend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("GridData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("backend.Models.Reportfilter", b =>
                {
                    b.Property<string>("Filtername")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("filtername");

                    b.Property<string>("Filterquery")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filterquery");

                    b.Property<string>("Reportname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reportname");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.ToTable("reportfilter");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("backend.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("backend.Models.Sage3", b =>
                {
                    b.Property<string>("Amountpaid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amountpaid");

                    b.Property<string>("Custref")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("custref");

                    b.Property<string>("Datepaid")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datepaid");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("Invoicefoundinsystem")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("invoicefoundinsystem");

                    b.Property<string>("Invoicenumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("invoicenumber");

                    b.Property<string>("Net")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("net");

                    b.Property<string>("Tax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tax");

                    b.Property<long?>("Transactionnumber")
                        .HasColumnType("bigint")
                        .HasColumnName("transactionnumber");

                    b.ToTable("sage3");
                });

            modelBuilder.Entity("backend.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("backend.Models.Setcompany", b =>
                {
                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address2");

                    b.Property<string>("Address3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address3");

                    b.Property<string>("Address4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address4");

                    b.Property<string>("Address5")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address5");

                    b.Property<string>("BankAccountDetails1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountDetails2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companycode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ContactTelephone1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactTelephone2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RegNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("regNumber");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("website");

                    b.ToTable("setcompany");
                });

            modelBuilder.Entity("backend.Models.StandardLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("StandardLetters");
                });

            modelBuilder.Entity("backend.Models.Total", b =>
                {
                    b.Property<string>("AccountRef")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("account_ref");

                    b.Property<decimal?>("Amountpaid")
                        .HasColumnType("money")
                        .HasColumnName("amountpaid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Invoicenumber")
                        .HasColumnType("int")
                        .HasColumnName("invoicenumber");

                    b.Property<decimal?>("Invoicetotal")
                        .HasColumnType("money")
                        .HasColumnName("invoicetotal");

                    b.Property<byte?>("Invoicetype")
                        .HasColumnType("tinyint")
                        .HasColumnName("invoicetype");

                    b.Property<decimal?>("Latepaymentinvoicenumber")
                        .HasColumnType("money")
                        .HasColumnName("latepaymentinvoicenumber");

                    b.Property<int?>("Leaseid")
                        .HasColumnType("int")
                        .HasColumnName("leaseid");

                    b.Property<DateTime?>("Paymentdate")
                        .HasColumnType("date")
                        .HasColumnName("paymentdate");

                    b.Property<int?>("Ppid")
                        .HasColumnType("int")
                        .HasColumnName("ppid");

                    b.Property<decimal?>("Settlementamount")
                        .HasColumnType("money")
                        .HasColumnName("settlementamount");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.ToTable("totals");
                });

            modelBuilder.Entity("backend.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("backend.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pword");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("backend.Models.BusinessSource", b =>
                {
                    b.HasOne("backend.Models.BusinessSource", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_BusinessSources_BusinessSources");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("backend.Models.ChasingLetter", b =>
                {
                    b.HasOne("backend.Models.LeasePaymentPoint", "LeasePaymentPoint")
                        .WithMany("ChasingLetters")
                        .HasForeignKey("LeasePaymentPointId")
                        .HasConstraintName("FK_ChasingLetters_LeasePaymentPoints")
                        .IsRequired();

                    b.HasOne("backend.Models.StandardLetter", "Template")
                        .WithMany("ChasingLetters")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK_ChasingLetters_StandardLetters")
                        .IsRequired();

                    b.Navigation("LeasePaymentPoint");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("backend.Models.CheckListItem", b =>
                {
                    b.HasOne("backend.Models.CheckListItem", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_CheckListItems_CheckListItems");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.HasOne("backend.Models.Sector", "LegalStatus")
                        .WithMany("CustomerLegalStatuses")
                        .HasForeignKey("LegalStatusId")
                        .HasConstraintName("FK_Customers_Sectors1");

                    b.HasOne("backend.Models.Sector", "Sector")
                        .WithMany("CustomerSectors")
                        .HasForeignKey("SectorId")
                        .HasConstraintName("FK_Customers_Sectors");

                    b.Navigation("LegalStatus");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("backend.Models.CustomerHistory", b =>
                {
                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("CustomerHistories")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_CustomerNotes_Customers")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("backend.Models.Document", b =>
                {
                    b.HasOne("backend.Models.Lease", "Lease")
                        .WithMany("Documents")
                        .HasForeignKey("LeaseId")
                        .HasConstraintName("FK_LeaseDocuments_Leases");

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("backend.Models.Lease", b =>
                {
                    b.HasOne("backend.Models.BusinessSource", "BusinessSource")
                        .WithMany("LeaseBusinessSources")
                        .HasForeignKey("BusinessSourceId")
                        .HasConstraintName("FK_Leases_BusinessSources")
                        .IsRequired();

                    b.HasOne("backend.Models.BusinessSource", "BusinessSourceItem")
                        .WithMany("LeaseBusinessSourceItems")
                        .HasForeignKey("BusinessSourceItemId")
                        .HasConstraintName("FK_Leases_BusinessSources1");

                    b.HasOne("backend.Models.Customer", "Customer")
                        .WithMany("Leases")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Leases_Customers")
                        .IsRequired();

                    b.HasOne("backend.Models.Sector", "LegalStatus")
                        .WithMany("LeaseLegalStatuses")
                        .HasForeignKey("LegalStatusId")
                        .HasConstraintName("FK_Leases_Sectors1")
                        .IsRequired();

                    b.HasOne("backend.Models.Sector", "Sector")
                        .WithMany("LeaseSectors")
                        .HasForeignKey("SectorId")
                        .HasConstraintName("FK_Leases_Sectors")
                        .IsRequired();

                    b.Navigation("BusinessSource");

                    b.Navigation("BusinessSourceItem");

                    b.Navigation("Customer");

                    b.Navigation("LegalStatus");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("backend.Models.LeaseCheckListItem", b =>
                {
                    b.HasOne("backend.Models.CheckListItem", "CheckListItem")
                        .WithMany("LeaseCheckListItems")
                        .HasForeignKey("CheckListItemId")
                        .HasConstraintName("FK_LeaseCheckListItems_CheckListItems1")
                        .IsRequired();

                    b.HasOne("backend.Models.Lease", "Lease")
                        .WithMany("LeaseCheckListItems")
                        .HasForeignKey("LeaseId")
                        .HasConstraintName("FK_LeaseCheckListItems_Leases")
                        .IsRequired();

                    b.Navigation("CheckListItem");

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("backend.Models.LeaseHistory", b =>
                {
                    b.HasOne("backend.Models.Document", "Document")
                        .WithMany("LeaseHistories")
                        .HasForeignKey("DocumentId")
                        .HasConstraintName("FK_LeaseHistory_LeaseDocuments");

                    b.HasOne("backend.Models.Lease", "Lease")
                        .WithMany("LeaseHistories")
                        .HasForeignKey("LeaseId")
                        .HasConstraintName("FK_LeaseHistory_Leases")
                        .IsRequired();

                    b.HasOne("backend.Models.LeasePaymentPoint", "PaymentPoint")
                        .WithMany("LeaseHistories")
                        .HasForeignKey("PaymentPointId")
                        .HasConstraintName("FK_LeaseHistory_LeasePaymentPoints");

                    b.Navigation("Document");

                    b.Navigation("Lease");

                    b.Navigation("PaymentPoint");
                });

            modelBuilder.Entity("backend.Models.LeaseItem", b =>
                {
                    b.HasOne("backend.Models.EquipmentCondition", "EquipmentCondition")
                        .WithMany("LeaseItems")
                        .HasForeignKey("EquipmentConditionId")
                        .HasConstraintName("FK_LeaseItems_EquipmentConditions")
                        .IsRequired();

                    b.HasOne("backend.Models.EquipmentType", "EquipmentType")
                        .WithMany("LeaseItems")
                        .HasForeignKey("EquipmentTypeId")
                        .HasConstraintName("FK_LeaseItems_EquipmentTypes")
                        .IsRequired();

                    b.HasOne("backend.Models.Lease", "Lease")
                        .WithMany("LeaseItems")
                        .HasForeignKey("LeaseId")
                        .HasConstraintName("FK_LeaseItems_Leases")
                        .IsRequired();

                    b.Navigation("EquipmentCondition");

                    b.Navigation("EquipmentType");

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("backend.Models.LeasePaymentPoint", b =>
                {
                    b.HasOne("backend.Models.Lease", "Lease")
                        .WithMany("LeasePaymentPoints")
                        .HasForeignKey("LeaseId")
                        .HasConstraintName("FK_LeasePaymentPoints_Leases")
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("backend.Models.RolePermission", b =>
                {
                    b.HasOne("backend.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.Sector", b =>
                {
                    b.HasOne("backend.Models.Sector", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Sectors_Sectors");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("backend.Models.UserPermission", b =>
                {
                    b.HasOne("backend.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Users", b =>
                {
                    b.HasOne("backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Roles")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.BusinessSource", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("LeaseBusinessSourceItems");

                    b.Navigation("LeaseBusinessSources");
                });

            modelBuilder.Entity("backend.Models.CheckListItem", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("LeaseCheckListItems");
                });

            modelBuilder.Entity("backend.Models.Customer", b =>
                {
                    b.Navigation("CustomerHistories");

                    b.Navigation("Leases");
                });

            modelBuilder.Entity("backend.Models.Document", b =>
                {
                    b.Navigation("LeaseHistories");
                });

            modelBuilder.Entity("backend.Models.EquipmentCondition", b =>
                {
                    b.Navigation("LeaseItems");
                });

            modelBuilder.Entity("backend.Models.EquipmentType", b =>
                {
                    b.Navigation("LeaseItems");
                });

            modelBuilder.Entity("backend.Models.Lease", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LeaseCheckListItems");

                    b.Navigation("LeaseHistories");

                    b.Navigation("LeaseItems");

                    b.Navigation("LeasePaymentPoints");
                });

            modelBuilder.Entity("backend.Models.LeasePaymentPoint", b =>
                {
                    b.Navigation("ChasingLetters");

                    b.Navigation("LeaseHistories");
                });

            modelBuilder.Entity("backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("backend.Models.Sector", b =>
                {
                    b.Navigation("CustomerLegalStatuses");

                    b.Navigation("CustomerSectors");

                    b.Navigation("InverseParent");

                    b.Navigation("LeaseLegalStatuses");

                    b.Navigation("LeaseSectors");
                });

            modelBuilder.Entity("backend.Models.StandardLetter", b =>
                {
                    b.Navigation("ChasingLetters");
                });
#pragma warning restore 612, 618
        }
    }
}
