/** Sample rows for UI until API replaces `new_main_form.asp` queries. */

export const MOCK_SECTORS = [
  { id: 1, description: 'Corporate IT' },
  { id: 2, description: 'Retail' },
]

/** Child sectors used as "Legal status" in legacy `cust_form.asp` (simplified). */
export const MOCK_LEGAL_STATUSES = [
  { id: 10, parentId: 1, description: 'Limited Company' },
  { id: 11, parentId: 1, description: 'Partnership' },
  { id: 20, parentId: 2, description: 'Sole Trader' },
]

export const MOCK_CUSTOMERS = [
  {
    id: 0,
    accountRef: 'ABBEYHEY',
    name: 'Abbey Hey Demo Ltd',
    town: 'Manchester',
    county: 'Greater Manchester',
    postcode: 'M18 8AA',
    contact: 'Demo Contact',
    phone: '0161 555 0199',
    balance: 0,
    paymentMethod: 1,
    sectorId: 1,
    legalStatusId: 10,
    notes: 'Sample customer matching legacy ACC REF example.',
    website: 'https://example.com',
    paperInvoices: true,
    emailInvoices: true,
    email: 'accounts@abbeyhey.demo',
  },
  {
    id: 1,
    accountRef: 'ACC1001',
    name: 'Acme Rentals Ltd',
    town: 'Manchester',
    county: 'Greater Manchester',
    postcode: 'M1 1AE',
    contact: 'Ms Jones',
    phone: '0161 555 0101',
    balance: 0,
    paymentMethod: 1,
    sectorId: 2,
    legalStatusId: 20,
    notes: '',
    website: '',
    paperInvoices: false,
    emailInvoices: true,
    email: 'hire@acme.demo',
  },
  {
    id: 2,
    accountRef: 'ACC2044',
    name: 'Brighton Tech Hire',
    town: 'Brighton',
    county: 'East Sussex',
    postcode: 'BN1 1AA',
    contact: 'Mr Patel',
    phone: '01273 555 0202',
    balance: 240.5,
    paymentMethod: 1,
    sectorId: 1,
    legalStatusId: 11,
    notes: 'Overdue balance on sample data.',
    website: '',
    paperInvoices: true,
    emailInvoices: true,
    email: '',
  },
  {
    id: 3,
    accountRef: 'ACC3050',
    name: 'Cambridge Audio Ltd',
    town: 'Cambridge',
    county: 'Cambridgeshire',
    postcode: 'CB2 1TP',
    contact: '',
    phone: '01223 555 0303',
    balance: -10,
    paymentMethod: 0,
    sectorId: 1,
    legalStatusId: 10,
    notes: '',
    website: '',
    paperInvoices: true,
    emailInvoices: false,
    email: '',
  },
  {
    id: 4,
    accountRef: 'ACC4102',
    name: 'Derby Equipment Co',
    town: 'Derby',
    county: 'Derbyshire',
    postcode: 'DE1 1AA',
    contact: 'Mrs Clark',
    phone: '01332 555 0404',
    balance: 89,
    paymentMethod: 1,
    sectorId: 2,
    legalStatusId: 20,
    notes: '',
    website: '',
    paperInvoices: true,
    emailInvoices: false,
    email: '',
  },
  {
    id: 5,
    accountRef: 'ACC5120',
    name: 'Exeter Marine Services',
    town: 'Exeter',
    county: 'Devon',
    postcode: 'EX1 1QA',
    contact: 'Capt. Reed',
    phone: '01392 555 0505',
    balance: 0,
    paymentMethod: 1,
    sectorId: 1,
    legalStatusId: 10,
    notes: '',
    website: '',
    paperInvoices: true,
    emailInvoices: false,
    email: '',
  },
]

export const MOCK_LEASE_ROWS = [
  {
    id: 101,
    accountRef: 'ACC1001',
    name: 'Acme Rentals Ltd',
    postcode: 'M1 1AE',
    contact: 'Ms Jones',
    phone: '0161 555 0101',
    leaseId: 5001,
    leaseDesc: 'Office laptops x12',
    startDate: '2024-01-15',
    endDate: '2027-01-14',
    paymentAmount: 420,
    leaseStatus: 'ActivePrim',
    termination: 'NO',
    balance: 0,
    paymentMethod: 1,
    payFreq: 'Monthly',
  },
  {
    id: 102,
    accountRef: 'ACC2044',
    name: 'Brighton Tech Hire',
    postcode: 'BN1 1AA',
    contact: 'Mr Patel',
    phone: '01273 555 0202',
    leaseId: 5002,
    leaseDesc: 'POS terminals',
    startDate: '2023-06-01',
    endDate: '2026-05-31',
    paymentAmount: 180,
    leaseStatus: 'ActiveSec',
    termination: 'YES',
    balance: 240.5,
    paymentMethod: 1,
    payFreq: 'Quarterly',
  },
  {
    id: 103,
    accountRef: 'ACC3050',
    name: 'Cambridge Audio Ltd',
    postcode: 'CB2 1TP',
    contact: '',
    phone: '01223 555 0303',
    leaseId: 5003,
    leaseDesc: 'Conference AV bundle',
    startDate: '2022-09-01',
    endDate: '2025-08-31',
    paymentAmount: 950,
    leaseStatus: 'Settled',
    termination: 'NO',
    balance: -10,
    paymentMethod: 0,
    payFreq: 'Annual',
  },
  {
    id: 100,
    accountRef: 'ABBEYHEY',
    name: 'Abbey Hey Demo Ltd',
    postcode: 'M18 8AA',
    contact: 'Demo Contact',
    phone: '0161 555 0199',
    leaseId: 4999,
    leaseDesc: 'Demo lease',
    startDate: '2025-01-01',
    endDate: '2028-12-31',
    paymentAmount: 199,
    leaseStatus: 'ActivePrim',
    termination: 'NO',
    balance: 0,
    paymentMethod: 1,
    payFreq: 'Monthly',
  },
]

/** @param {string} ref */
export function findCustomerByAccountRef(ref) {
  const u = String(ref ?? '').trim().toUpperCase()
  return MOCK_CUSTOMERS.find((c) => c.accountRef.toUpperCase() === u) ?? null
}

/** @param {string} accountRef */
export function leasesForAccount(accountRef) {
  const u = String(accountRef ?? '').trim().toUpperCase()
  return MOCK_LEASE_ROWS.filter((r) => r.accountRef.toUpperCase() === u)
}
